### PR TITLE
docs: fix broken links

### PR DESCRIPTION
**Pull request by Unisay**
- [x] Pull request template link points at `cardano-wallet` repo.
- [x] Replace the "task" template link with the link to a folder of templates per issue type.

### CODE REVIEW

**Review by HeinrichApfelmus — APPROVED** [review]
Thanks! 😊

**Comment by Unisay** [comment]
I don't know why build fails, @rvl do you know if failing build is cause by my change or should I ignore it for now?

**Review by rvl — APPROVED** [review]
Thanks

**Comment by rvl** [comment]
Sorry about the build failures.
Something got messed up with nix flake lock files, which I don't understand.
I made PR #22 to fix it.

**Pull request merged**
